config/routes.rb
Newyorksunshine::Application.routes.draw do
  mount Spree::Core::Engine, :at => '/'
end

Spree::Core::Engine.add_routes do

  concern :images do
    resources :images
  end


  namespace :admin do

    put 'feed_items', to: 'feed_items#update_batch', as: 'update_batch_feed_items'
    resources :feed_items

    put 'surf_club_images', to: 'surf_club_images#update_batch', as: 'update_batch_suf_club_images'
    resources :surf_club_images

    # resources :lookbooks, shallow: true do
    #   resources :slides, shallow: true do
    #     resources :slide_images
    #   end
    # end

    resources :lookbooks do
      put 'slides', to: 'slides#update_batch', as: 'update_batch_slides'
      resources :slides
      # resources :slides, as: 'slidezs'
    end

    resources :press_items

    resources :posts do
      resources :post_images
    end

    put 'stockists/sort', to: 'stockists#sort', as: 'sort_stockists'
    resources :stockists

    resources :contents
    resource :about
    resource :returns_exchanges

    # Art section
    resource :art, only: [:show]
    resource :artists_statement
    resources :works
  end


  # Add your extension routes here
  # get 'lookbooks', :to => 'lookbooks#index'
  # get 'lookbooks/:id', :to => 'lookbooks#show'

  resources :lookbooks

  get 'news', to: 'news#index'
  get 'tagged/:tag', to: 'news#index', as: :tag
  get 'post/:id', to: 'news#show', as: :post

  # resources :posts

  # This needs to change
  # get 'tagged/:tag', :to => 'news#tagged'

  get 'press', to: 'press#index'

  get 'art', :to => 'arts#index'

  get 'stockists', :to => 'stockists#index'

  get 'surfclub', :to => 'surfclub#index'

  get 'about', :to => 'about#index'

  get 'returns-exchanges', :to => 'returns_exchanges#index'

  post 'subscribe' => 'subscribe#process_form'

end

app/models/spree/feed_item.rb
class Spree::FeedItem < ActiveRecord::Base
  before_save :destroy_image?

  belongs_to :product, :dependent => :destroy
  belongs_to :lookbook
  belongs_to :post

  enum category: [ "Product", "Lookbook", "Post", "Other" ]

  # has_attached_file :attachment, :styles => { :cropped => "1080x1620>", :thumb => "100x150#" }
  has_attached_file :attachment, :styles => { :cropped => "856x1248>", :thumb => "100x150#" }

  attr_accessor :delete_attachment
  before_validation { attachment.clear if delete_attachment == '1' }


  validates_attachment_content_type :attachment, :content_type => /\Aimage\/.*\Z/

  default_scope { order('position') }


  private

  def destroy_image?
    self.image.clear if @image_delete == "1"
  end

end

app/controllers/spree/admin/feed_items_controller.rb
module Spree
  module Admin
    class FeedItemsController < ResourceController
      before_action :build_category_options, only: [:new, :edit]
      before_action :set_feed_item, only: [:show, :edit, :update, :destroy]

      def index

        @feed_items = FeedItem.all
      end

      def show
      end

      def new
        @feed_item = FeedItem.new

      end

      def edit
      end

      def create
        @feed_item = FeedItem.new(admin_feed_item_params)

        respond_to do |format|
          if @feed_item.save
            format.html { redirect_to admin_feed_items_path, notice: 'Home Page feed item was successfully created.' }
            format.json { render action: 'show', status: :created, location: @feed_item }
          else
            format.html { render action: 'new' }
            format.json { render json: @feed_item.errors, status: :unprocessable_entity }
          end
        end
      end

      def update
        if @feed_item.update(admin_feed_item_params)
          redirect_to admin_feed_items_path, notice: 'Feed Item was sucessfully updated.'
        else
          render :edit
        end
      end

      def update_batch
        params[:feeditem].each_with_index do |id, i|
          FeedItem.find(id).update_column(:position, i + 1)
        end
        render nothing: true
      end

      def destroy
        @feed_item.destroy
        respond_to do |format|
          format.html { redirect_to admin_feed_items_url, notice: 'Feed Item was successfully destroyed.' }
          format.json { head :no_content }
        end
      end


      private

        def set_feed_item
          @feed_item = FeedItem.find(params[:id])
        end

        def build_category_options
          @products = Product.all.order("name")
          @posts = Post.unscoped.all.order("title")
          @lookbooks = Lookbook.all.order("name")

          @category_options = FeedItem.categories.keys
        end


        def admin_feed_item_params
          params.require(:feed_item).permit!
        end


    end
  end
end

app/views/spree/admin/feed_items/_feed_item.erb
<div class="feed-item" data-id="<%= id %>" id="feeditem_<%= id %>">
  <%= image_tag image_src, { width: 100 } %>
  <div class="info">

    <% if(defined? href) %>

      <%= link_to href, { :target => "_blank" } do %>
        <%= category %>
        <br>
        <%= title %>
      <% end %>

    <% else %>

      <div>
        <%= category %>
        <br>
        <%= title %>
      </div>


    <% end %>


    <p class="actions">
      <%= link_to "edit", edit_admin_feed_item_path(id), :class => "fa fa-edit no-text" %>
      &nbsp;
      <%= link_to "delete", admin_feed_item_path(id), method: :delete, data: { confirm: 'Are you sure?' }, :class => "fa fa-trash no-text" %>
    </p>

  </div>
</div>

app/views/spree/admin/feed_items/_form.html.erb
<%= form_for [:admin, @feed_item] do |f|  %>

  <% if @feed_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feed_item.errors.count, "error") %> prohibited this feed_item from being saved:</h2>

      <ul>
      <% @feed_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.field_container :category do %>
    <%= f.label :category %>
    <br>
    <%= f.select :category, options_for_select(@category_options, selected: @feed_item.category), { prompt: "Select a Category", class: 'select21' } %>
  <% end %>

  <div class="field-group" data-type="Product">
    <%= f.field_container :product do %>
      <%= f.label :product %>
      <br>
      <%= f.collection_select :product_id, @products, :id, :name, { prompt: true, class: 'select2' } %>
    <% end %>
  </div>

  <div class="field-group" data-type="Lookbook">
    <%= f.field_container :lookbook do %>
      <%= f.label :lookbook %>
      <br>
      <%= f.collection_select :lookbook_id, @lookbooks, :id, :name, { prompt: true, class: 'select2' } %>
    <% end %>
  </div>

  <div class="field-group" data-type="Post">
    <%= f.field_container :post do %>
      <%= f.label :post %>
      <br>
      <%= f.collection_select :post_id, @posts, :id, :title, { prompt: true, class: 'select2' } %>
    <% end %>
  </div>

  <div class="field-group" data-type="Other">
    <p>enter custom fields</p>

    <%= f.field_container  :superheading do %>
      <%= f.label :superheading %>
      <br>
      <%= f.text_field :superheading %>
    <% end %>


    <%= f.field_container  :title do %>
      <%= f.label :title %>
      <br>
      <%= f.text_field :title %>
    <% end %>


    <%= f.field_container  :href do %>
      <%= f.label :href, 'Link URL' %>
      <br>
      <%= f.text_field :href %>
    <% end %>
  </div>

  <%= f.field_container  :attachment do %>
    <%= f.label :attachment, 'Image' %>
    <br>
    <%= f.file_field :attachment %>
    <% if f.object.attachment.exists? %>
      <%= link_to image_tag(f.object.attachment.url(:thumb)), f.object.attachment.url %>
    <% end %>
  <% end %>

  <%= f.check_box :delete_attachment %>
  <%= f.label :delete_attachment %>

  <%= f.submit %> or <%= link_to "Cancel", admin_feed_items_path %>

<% end %>

app/views/spree/admin/feed_items/_lookbook_feed_item.erb
<% image_source = feed_item.attachment_file_name != nil ? feed_item.attachment.url : feed_item.lookbook.slides[0].slide_images[0].attachment.url(:thumb) %>
<%= render :partial => "feed_item", :locals => { :id => feed_item.id, :image_src => image_source, :category => "LOOKBOOK", :title => feed_item.lookbook.name, :href => lookbook_path(feed_item.lookbook.id) } %>

app/views/spree/admin/feed_items/_other_feed_item.erb
<%= render :partial => "feed_item", :locals => { :id => feed_item.id, :image_src => feed_item.attachment.url(:cropped), :category => feed_item.superheading, :title => feed_item.title, :href => feed_item.href } %>

app/views/spree/admin/feed_items/_post_feed_item.erb
<% image_source = feed_item.attachment_file_name != nil ? feed_item.attachment.url : feed_item.post.post_images[0].attachment.url(:thumb) %>
<%= render :partial => "feed_item", :locals => { :id => feed_item.id, :image_src => image_source, :category => "NEWS", :title => feed_item.post.title, :href => post_path(feed_item.post) } %>

app/views/spree/admin/feed_items/_product_feed_item.erb
<% if feed_item.product %>
  <% image_source = feed_item.attachment.present? ? feed_item.attachment.url(:cropped) : "//placehold.it/856x1248" %>
  <%= render :partial => "feed_item", :locals => { :id => feed_item.id, :image_src => image_source, :category => "SHOP", :title => feed_item.product.name, :href => product_path(feed_item.product) } %>
<% else %>

  <div class="feed-item" data-id="<%= feed_item.id %>" id="feeditem_<%= feed_item.id %>">

    <div class="info">
      <p>No product to display</p>
      <p class="actions">
        <%= link_to "edit", edit_admin_feed_item_path(feed_item.id), :class => "fa fa-edit no-text" %>
        &nbsp;
        <%= link_to "delete", admin_feed_item_path(feed_item.id), method: :delete, data: { confirm: 'Are you sure?' }, :class => "fa fa-trash no-text" %>
      </p>
    </div>

  </div>

<% end %>

app/views/spree/admin/feed_items/edit.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:edit_feed_item) %>
<% end %>



<%= render 'form' %>

app/views/spree/admin/feed_items/index.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:feed_items) %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:new_feed_item), new_object_url, class: "btn-success", icon: 'add' %>
<% end %>


<div id="feed-items">
  <% @feed_items.each do |feed_item| %>
    <%= render :partial => "#{feed_item.category.downcase}_feed_item", :locals => { :feed_item => feed_item } %>
  <% end %>
</div>

app/views/spree/admin/feed_items/new.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:new_feed_item) %>
<% end %>




<%= render 'form' %>