config/routes.rb
Newyorksunshine::Application.routes.draw do
  mount Spree::Core::Engine, :at => '/'
end

Spree::Core::Engine.add_routes do

  concern :images do
    resources :images
  end


  namespace :admin do

    put 'feed_items', to: 'feed_items#update_batch', as: 'update_batch_feed_items'
    resources :feed_items

    put 'surf_club_images', to: 'surf_club_images#update_batch', as: 'update_batch_suf_club_images'
    resources :surf_club_images

    # resources :lookbooks, shallow: true do
    #   resources :slides, shallow: true do
    #     resources :slide_images
    #   end
    # end

    resources :lookbooks do
      put 'slides', to: 'slides#update_batch', as: 'update_batch_slides'
      resources :slides
      # resources :slides, as: 'slidezs'
    end

    resources :press_items

    resources :posts do
      resources :post_images
    end

    put 'stockists/sort', to: 'stockists#sort', as: 'sort_stockists'
    resources :stockists

    resources :contents
    resource :about
    resource :returns_exchanges

    # Art section
    resource :art, only: [:show]
    resource :artists_statement
    resources :works
  end


  # Add your extension routes here
  # get 'lookbooks', :to => 'lookbooks#index'
  # get 'lookbooks/:id', :to => 'lookbooks#show'

  resources :lookbooks

  get 'news', to: 'news#index'
  get 'tagged/:tag', to: 'news#index', as: :tag
  get 'post/:id', to: 'news#show', as: :post

  # resources :posts

  # This needs to change
  # get 'tagged/:tag', :to => 'news#tagged'

  get 'press', to: 'press#index'

  get 'art', :to => 'arts#index'

  get 'stockists', :to => 'stockists#index'

  get 'surfclub', :to => 'surfclub#index'

  get 'about', :to => 'about#index'

  get 'returns-exchanges', :to => 'returns_exchanges#index'

  post 'subscribe' => 'subscribe#process_form'

end

app/models/spree/stockist.rb
class Spree::Stockist < ActiveRecord::Base

  enum region: [ "North America", "International" ]

  default_scope { order('region, position') }


end

app/controllers/spree/admin/stockists_controller.rb
module Spree
  module Admin
    class StockistsController < ResourceController
      before_action :set_admin_stockist, only: [:show, :edit, :update, :destroy]
      before_action :build_region_array, only: [:new, :edit]

      # GET /spree/admin/stockists
      def index

        @stockists = Stockist.all.group_by(&:region)
      end

      # GET /spree/admin/stockists/1
      def show
        session[:return_to] ||= request.referer
        redirect_to( :action => :edit )
      end

      # GET /spree/admin/stockists/new
      def new
        @admin_stockist = Stockist.new
      end

      # GET /spree/admin/stockists/1/edit
      def edit
      end

      # POST /spree/admin/stockists
      def create
        @admin_stockist = Stockist.new(admin_stockist_params)

        if @admin_stockist.save
          redirect_to admin_stockists_url, notice: 'Stockist was successfully created.'
        else
          render :new
        end
      end

      # PATCH/PUT /spree/admin/stockists/1
      def update
        if @admin_stockist.update(admin_stockist_params)
          redirect_to admin_stockists_url, notice: 'Stockist was successfully updated.'
        else
          render :edit
        end
      end

      def sort
        params[:stockist].each_with_index do |id, i|
          Stockist.find(id).update_column(:position, i + 1)
        end
        render nothing: true
      end

      # DELETE /spree/admin/stockists/1
      def destroy
        @admin_stockist.destroy
        redirect_to admin_stockists_url, notice: 'Stockist was successfully destroyed.'
      end

      private
        # Use callbacks to share common setup or constraints between actions.
        def set_admin_stockist
          @admin_stockist = Stockist.find(params[:id])
        end

        def build_region_array
          # @regions_hash = Stockist.regions.collect { |region| region }
          @regions_hash = Stockist.regions.keys
        end

        # Only allow a trusted parameter "white list" through.
        def admin_stockist_params
          params.require(:stockist).permit!
        end

    end
  end
end

app/controllers/spree/stockists_controller.rb
module Spree
  class StockistsController < Spree::BaseController
    def index
      @stockists = Stockist.all.group_by(&:region)
    end
  end
end

app/helpers/spree/admin/stockists_helper.rb
module Spree::Admin::StockistsHelper
end

app/helpers/spree/stockists_helper.rb
module Spree::StockistsHelper

  def nice_url(url)
    # return url
    return url.to_s.sub(/^https?\:\/\//, '').sub(/^www./,'').sub(/\//,'')
    # return url
  end

end

app/views/spree/admin/stockists/_datatable.html.erb
<table class="table">
  <colgroup>
    <col style="width: 15%;">
    <col style="width: 50%;">
    <col style="width: 15%;">
    <col style="width: 15%;">
    <col style="width: 1%;">
    <col style="width: 4%;">
  </colgroup>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Phone Number</th>
      <th>Link</th>
      <th class="actions"></th>
    </tr>
  </thead>

  <tbody class="zortable" data-sort="<%= admin_sort_stockists_path %>">
    <% stockists.each do |stockist| %>
      <tr class="sortable-item" id="<%= dom_id(stockist) %>">
        <td><%= stockist.name %></td>
        <td>
          <address><%= stockist['address'] %></address>
        </td>
        <td>
          <% if (defined?(stockist['phone_number'])) %>
            <a class="phone-number" href="tel:<%= stockist['phone_number'] %>"><%= stockist['phone_number'] %></a>
          <% end %>
        </td>
        <td>
          <%= link_to stockist.link, stockist.link %>
        </td>
        <td class="actions">
          <%= link_to_edit stockist, :no_text => true, :class => 'edit' %>
          &nbsp;
          <%= link_to_delete stockist, :no_text => true %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/spree/admin/stockists/_form.html.erb
<%= form_for [:admin, @admin_stockist] do |f| %>
  <% if @admin_stockist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_stockist.errors.count, "error") %> prohibited this admin_stockist from being saved:</h2>

      <ul>
      <% @admin_stockist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="row">

    <div class="one-third column alpha">
      <%= f.field_container :name do %>
        <%= f.label :name %>
        <%= f.text_field :name, :class => "fullwidth" %>
      <% end %>
    </div>

    <div class="one-third column">
      <%= f.field_container :address do %>
        <%= f.label :address %>
        <%= f.text_field :address, :class => "fullwidth" %>
      <% end %>
    </div>

    <div class="one-third column omega">
      <%= f.field_container :region do %>
        <%= f.label :region %>

        <%= f.select :region, options_for_select(@regions_hash, selected: @admin_stockist.region), {}, class: 'select2 fullwidth' %>
      <% end %>
    </div>

  </div>

  <div class="row">

    <div class="one-third column alpha">
      <%= f.field_container :phone_number do %>
        <%= f.label :phone_number %>
        <%= f.text_field :phone_number, :class => "fullwidth" %>
      <% end %>
    </div>

    <div class="one-third column">
      <%= f.field_container :link do %>
        <%= f.label :link %>
        <%= f.text_field :link, :class => "fullwidth" %>
      <% end %>
    </div>

    <div class="one-third column omega">
      <%= f.field_container :position do %>
        <%= f.label :position %>
        <%= f.text_field :position, :class => "fullwidth" %>
      <% end %>
    </div>

  </div>


  <div class="row">
    <div class="actions">
      <%= f.submit %>
      or
      <%= link_to 'Cancel', admin_stockists_path %>
    </div>
  </div>

<% end %>

app/views/spree/admin/stockists/edit.html.erb
<% content_for :page_actions do %>
  <li><%= button_link_to Spree.t(:back_to_stockists_list), admin_stockists_url, :icon => 'arrow-left' %></li>
  <li id="new_product_link">
    <%= button_link_to Spree.t(:new_stockist), new_object_url, { :icon => 'plus', :id => 'admin_new_product' } %>
  </li>
<% end %>




<h1>Editing admin_stockist</h1>

<%= render 'form' %>

app/views/spree/admin/stockists/index.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:stockists) %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:new_stockist), new_object_url, icon: 'plus', class: "btn-success" %>
<% end %>



<% @stockists.each do |stockist_region, stockists| %>

  <h2><%= stockist_region %></h2>

  <%= render :partial => "datatable", :locals => { :stockists => stockists } %>

<% end %>

app/views/spree/admin/stockists/new.html.erb
<h1>New Stockist</h1>

<%= render 'form' %>

app/views/spree/admin/stockists/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_admin_stockist_path(@admin_stockist) %> |
<%= link_to 'Back', admin_stockists_path %>