config/routes.rb
Newyorksunshine::Application.routes.draw do
  mount Spree::Core::Engine, :at => '/'
end

Spree::Core::Engine.add_routes do

  concern :images do
    resources :images
  end


  namespace :admin do

    put 'feed_items', to: 'feed_items#update_batch', as: 'update_batch_feed_items'
    resources :feed_items

    put 'surf_club_images', to: 'surf_club_images#update_batch', as: 'update_batch_suf_club_images'
    resources :surf_club_images

    # resources :lookbooks, shallow: true do
    #   resources :slides, shallow: true do
    #     resources :slide_images
    #   end
    # end

    resources :lookbooks do
      put 'slides', to: 'slides#update_batch', as: 'update_batch_slides'
      resources :slides
      # resources :slides, as: 'slidezs'
    end

    resources :press_items

    resources :posts do
      resources :post_images
    end

    put 'stockists/sort', to: 'stockists#sort', as: 'sort_stockists'
    resources :stockists

    resources :contents
    resource :about
    resource :returns_exchanges

    # Art section
    resource :art, only: [:show]
    resource :artists_statement
    resources :works
  end


  # Add your extension routes here
  # get 'lookbooks', :to => 'lookbooks#index'
  # get 'lookbooks/:id', :to => 'lookbooks#show'

  resources :lookbooks

  get 'news', to: 'news#index'
  get 'tagged/:tag', to: 'news#index', as: :tag
  get 'post/:id', to: 'news#show', as: :post

  # resources :posts

  # This needs to change
  # get 'tagged/:tag', :to => 'news#tagged'

  get 'press', to: 'press#index'

  get 'art', :to => 'arts#index'

  get 'stockists', :to => 'stockists#index'

  get 'surfclub', :to => 'surfclub#index'

  get 'about', :to => 'about#index'

  get 'returns-exchanges', :to => 'returns_exchanges#index'

  post 'subscribe' => 'subscribe#process_form'

end

app/models/spree/work.rb
class Spree::Work < ActiveRecord::Base

  default_scope { order('position') }

  has_attached_file :attachment,
  :styles => { :large => "992x992>" },
  :default_url => "/images/:style/missing.png"

  validates_attachment_content_type :attachment, :content_type => /\Aimage\/.*\Z/
  validates :attachment, presence: true


end

app/controllers/spree/admin/works_controller.rb
module Spree
  module Admin
    class WorksController < ResourceController
      before_action :set_admin_work, only: [:show, :edit, :update, :destroy]

      # GET /spree/admin/works
      def index
        @admin_works = Work.all
      end

      # GET /spree/admin/works/1
      def show
      end

      # GET /spree/admin/works/new
      def new
        @admin_work = Work.new
      end

      # GET /spree/admin/works/1/edit
      def edit
      end

      # POST /spree/admin/works
      def create
        @admin_work = Work.new(admin_work_params)

        if @admin_work.save
          redirect_to admin_art_url, notice: 'Work was successfully created.'
        else
          render :new
        end
      end

      # PATCH/PUT /spree/admin/works/1
      def update
        if @admin_work.update(admin_work_params)
          redirect_to admin_art_url, notice: 'Work was successfully updated.'
        else
          render :edit
        end
      end

      # DELETE /spree/admin/works/1
      def destroy
        @admin_work.destroy
        redirect_to admin_art_url, notice: 'Work was successfully destroyed.'
      end

      private
        # Use callbacks to share common setup or constraints between actions.
        def set_admin_work
          @admin_work = Work.unscoped.find(params[:id])
        end

        # Only allow a trusted parameter "white list" through.
        def admin_work_params
          params.require(:work).permit!
        end
    end
  end
end

app/helpers/spree/admin/works_helper.rb
module Spree::Admin::WorksHelper
end

app/views/spree/admin/works/_form.html.erb
<%= form_for [:admin, @admin_work] do |f| %>
  <% if @admin_work.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_work.errors.count, "error") %> prohibited this admin_work from being saved:</h2>

      <ul>
      <% @admin_work.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="row">
    <div class="sixteen columns alpha omega">
      <%= f.field_container :attachment do %>
        <%= f.label :attachment %>
        <%= f.file_field :attachment, :class => "fullwidth" %>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="sixteen columns alpha omega">
      <%= f.field_container :caption do %>
        <%= f.label :caption %>
        <%= f.text_area :caption, :class => "fullwidth" %>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="sixteen columns alpha omega">
      <%= f.field_container :published do %>
        <%= f.check_box :published, :class => "fullwidth" %> <%= f.label :published %>
      <% end %>
    </div>
  </div>




  <div class="actions">
    <%= f.submit %> or <%= link_to 'Cancel', admin_works_path %>
  </div>
<% end %>

app/views/spree/admin/works/edit.html.erb
<h1>Editing admin_work</h1>

<%= render 'form' %>

app/views/spree/admin/works/index.html.erb
<h1>Listing admin_works</h1>

<table class="table">
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_works.each do |admin_work| %>
      <tr>
        <td><%= link_to 'Edit', edit_admin_work_path(admin_work) %></td>
        <td><%= link_to 'Destroy', admin_work_path(admin_work), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Work', new_admin_work_path %>

app/views/spree/admin/works/new.html.erb
<h1>New admin_work</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_works_path %>

app/views/spree/admin/works/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_admin_work_path(@admin_work) %> |
<%= link_to 'Back', admin_works_path %>