config/routes.rb
Newyorksunshine::Application.routes.draw do
  mount Spree::Core::Engine, :at => '/'
end

Spree::Core::Engine.add_routes do

  concern :images do
    resources :images
  end


  namespace :admin do

    put 'feed_items', to: 'feed_items#update_batch', as: 'update_batch_feed_items'
    resources :feed_items

    put 'surf_club_images', to: 'surf_club_images#update_batch', as: 'update_batch_suf_club_images'
    resources :surf_club_images

    # resources :lookbooks, shallow: true do
    #   resources :slides, shallow: true do
    #     resources :slide_images
    #   end
    # end

    resources :lookbooks do
      put 'slides', to: 'slides#update_batch', as: 'update_batch_slides'
      resources :slides
      # resources :slides, as: 'slidezs'
    end

    resources :press_items

    resources :posts do
      resources :post_images
    end

    put 'stockists/sort', to: 'stockists#sort', as: 'sort_stockists'
    resources :stockists

    resources :contents
    resource :about
    resource :returns_exchanges

    # Art section
    resource :art, only: [:show]
    resource :artists_statement
    resources :works
  end


  # Add your extension routes here
  # get 'lookbooks', :to => 'lookbooks#index'
  # get 'lookbooks/:id', :to => 'lookbooks#show'

  resources :lookbooks

  get 'news', to: 'news#index'
  get 'tagged/:tag', to: 'news#index', as: :tag
  get 'post/:id', to: 'news#show', as: :post

  # resources :posts

  # This needs to change
  # get 'tagged/:tag', :to => 'news#tagged'

  get 'press', to: 'press#index'

  get 'art', :to => 'arts#index'

  get 'stockists', :to => 'stockists#index'

  get 'surfclub', :to => 'surfclub#index'

  get 'about', :to => 'about#index'

  get 'returns-exchanges', :to => 'returns_exchanges#index'

  post 'subscribe' => 'subscribe#process_form'

end

app/controllers/spree/admin/arts_controller.rb
module Spree
  module Admin
    class ArtsController < Spree::Admin::BaseController

      def show
        @artist_statement = Content.where(key: "artist_statement").first_or_create.value
        @admin_works = Work.unscoped.order('position')
      end

    end
  end
end

app/controllers/spree/arts_controller.rb
module Spree
  class ArtsController < Spree::BaseController
    def index
      @artist_statement = Content.where(key: "artist_statement").first_or_create.value
      @works = Work.unscoped.all
    end
  end
end

app/views/spree/admin/arts/show.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:Art) %>
<% end %>



<%= @artist_statement %>
<p>
<%= link_to "Edit", edit_admin_artists_statement_path, class: "button" %></p>

<hr>

<p><%= button_link_to "New Work", new_admin_work_path, class: "btn-success", icon: 'add' %></p>


<div class="works">
  <% @admin_works.each do |admin_work| %>
    <div class="work">
      <%= image_tag admin_work.attachment %>
      <div class="actions">
        <%= link_to 'Edit', edit_admin_work_path(admin_work) %>
        <%= link_to 'Destroy', admin_work_path(admin_work), method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>
    </div>
  <% end %>
</div>